defaultPortal: local-cms-dev
portals:
  - name: local-cms-dev
    portalId: 21279197
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLPh2brMMBILAAUAAAAAAAwAQAIY3eOSCiCrhIcFKO7pDDIUak878riDogd8kypC6GtnSQ2YoPM6JgAABEEAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAPAAAAABEQhTcApU0ku8hBZ74kIFPRLqoIj-on0oDbmExUgBaAA
        expiresAt: '2022-11-30T07:00:41.783Z'
    personalAccessKey: >-
      CiQyMDIwMzEzOS0yMWZjLTQ2MDMtYjQzMy0wOGFjMzA3M2M5OTMQ3eOSChirhIcFKhkABeaRgjCTKgCd0VwBvWbTX6y0CovZkz9GSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
